### ISSUE TITLE
Hidden dependency making Fluffy crash

### ISSUE THREAD

**Issue by henrikstranneheim** [J35P312/fluffy#8]
The scripts in: [fluffy](https://github.com/J35P312/fluffy)/[fluffy](https://github.com/J35P312/fluffy/tree/master/fluffy)/scripts/ are executed in a sbatch scripts. However they do not activate any environment, but rather use the python binary that happens to be available, this is an unexpected behavior that makes the pipeline crash unless the "correct" python version and dependencies happens to be available.

For instance like this:

```
Traceback (most recent call last):
  File "/home/proj/production/bin/miniconda3/envs/P_fluffy/lib/python3.7/site-packages/fluffy/scripts/generate_csv.py", line 7, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

Would is be possible to include these scripts in a singularity image or the main Fluffy installation?

**Comment by J35P312** [comment]
Hello!
interesting! Numpy is not a hidden dependency, it is listed in the requirements.txt and pipfile.
I notice you are using the correct environment, but it seems you have not installed these dependencies.

I recommend you to clean up your environment, and then install fluffy through pip:

pip install cg-fluffy.

good luck!

**Comment by henrikstranneheim** [comment]
Using this manually modified script:

```
θ64° 3d [hiseq.clinical@hasta:~] [P_base] $ cat test.sh
#!/bin/bash

#SBATCH -e /home/proj/production/nipt/cases/simplesalmon/output/logs/test.err
#SBATCH -o /home/proj/production/nipt/cases/simplesalmon/output/logs/test.out
#SBATCH -J summarizebatch-59a24947b74ea8c777f5439dc7175ff315040e47-2022-11-16

#SBATCH --account=production
#SBATCH --time=5:00:00
#SBATCH --ntasks=4
#SBATCH --mem=20G
#SBATCH --qos=normal

set -eo pipefail -o nounset


###



python /home/proj/production/bin/miniconda3/envs/P_fluffy/lib/python3.7/site-packages/fluffy/scripts/generate_csv.py --folder /home/proj/production/nipt/cases/simplesalmon/output --samplesheet /home/proj/production/nipt/cases/simplesalmon/SampleSheet_2116723_NIPT.csv --Zscore 5 --minCNV 10000000 --maxGCD 2.0 --maxATD 7.0 --maxbin2bin 0.0008 --maxdup 0.15 --minreads 20000000 > /home/proj/production/nipt/cases/simplesalmon/output/2116723_NIPT.2pass.csv
python /home/proj/production/bin/miniconda3/envs/P_fluffy/lib/python3.7/site-packages/fluffy/scripts/merge_csv.py /home/proj/production/nipt/cases/simplesalmon/output/2116723_NIPT.1pass.csv /home/proj/production/nipt/cases/simplesalmon/output/2116723_NIPT.2pass.csv > /home/proj/production/nipt/cases/simplesalmon/output/2116723_NIPT.csv
θ63° 3d [hiseq.clinical@hasta:~] [P_base] $
```

When submitting from conda env `P_base` - an environment without `numpy` 🚫 

```
θ63° 3d [hiseq.clinical@hasta:~] [P_base] $ sbatch test.sh
Submitted batch job 4029001
θ62° 3d [hiseq.clinical@hasta:~] [P_base] $ cat /home/proj/production/nipt/cases/simplesalmon/output/logs/test.err
Traceback (most recent call last):
  File "/home/proj/production/bin/miniconda3/envs/P_fluffy/lib/python3.7/site-packages/fluffy/scripts/generate_csv.py", line 7, in <module>
    import numpy
ModuleNotFoundError: No module named 'numpy'
```

There is no numpy in P_base

```
θ60° 3d [hiseq.clinical@hasta:~] [P_base] $ conda list
# packages in environment at /home/proj/production/bin/miniconda3/envs/P_base:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_18    conda-forge
libgomp                   12.2.0              h65d4601_18    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.5                h166bdaf_2    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
python                    3.10.6          ha86cf86_0_cpython    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

When launching from a conda env with python and numpy ✅ 

```
θ60° 3d [hiseq.clinical@hasta:~] [P_fluffy] 4s $ sbatch test.sh
Submitted batch job 4029002
θ63° 3d [hiseq.clinical@hasta:~] [P_fluffy] $ scontrol show jobid=4029002
JobId=4029002 JobName=summarizebatch-59a24947b74ea8c777f5439dc7175ff315040e47-2022-11-16
   UserId=hiseq.clinical(2191) GroupId=users(100) MCS_label=N/A
   Priority=114 Nice=0 Account=production QOS=normal WCKey=*default
   JobState=COMPLETING Reason=None Dependency=(null)
   Requeue=1 Restarts=0 BatchFlag=1 Reboot=0 ExitCode=0:0
   RunTime=00:00:17 TimeLimit=05:00:00 TimeMin=N/A
   SubmitTime=2022-11-23T15:53:26 EligibleTime=2022-11-23T15:53:26
   AccrueTime=2022-11-23T15:53:26
   StartTime=2022-11-23T15:53:27 EndTime=2022-11-23T15:53:44 Deadline=N/A
   PreemptTime=None SuspendTime=None SecsPreSuspend=0
   LastSchedEval=2022-11-23T15:53:27
   Partition=core AllocNode:Sid=hasta:22136
   ReqNodeList=(null) ExcNodeList=(null)
   NodeList=compute-0-2
   BatchHost=compute-0-2
   NumNodes=1 NumCPUs=4 NumTasks=4 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=4,mem=20G,node=1,billing=4
   Socks/Node=* NtasksPerN:B:S:C=0:0:*:* CoreSpec=*
   MinCPUsNode=4 MinMemoryNode=20G MinTmpDiskNode=0
   Features=(null) DelayBoot=00:00:00
   OverSubscribe=OK Contiguous=0 Licenses=(null) Network=(null)
   Command=/home/hiseq.clinical/test.sh
   WorkDir=/home/hiseq.clinical
   StdErr=/home/proj/production/nipt/cases/simplesalmon/output/logs/test.err
   StdIn=/dev/null
   StdOut=/home/proj/production/nipt/cases/simplesalmon/output/logs/test.out
   Power=

θ60° 3d [hiseq.clinical@hasta:~] [P_fluffy] $ cat /home/proj/production/nipt/cases/simplesalmon/output/logs/test.err
θ60° 3d [hiseq.clinical@hasta:~] [P_fluffy] $
```

```
θ60° 3d [hiseq.clinical@hasta:~] [P_fluffy] $ conda list
# packages in environment at /home/proj/production/bin/miniconda3/envs/P_fluffy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
cg-fluffy                 3.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
coreutils                 9.1                  h166bdaf_0    conda-forge
curl                      7.86.0               h7bff187_1    conda-forge
humanfriendly             10.0                     pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libcurl                   7.86.0               h7bff187_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
nextflow                  21.04.0              h4a94de4_0    bioconda
numpy                     1.21.0                   pypi_0    pypi
openjdk                   8.0.152              h7b6447c_3
openssl                   1.1.1s               h166bdaf_0    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
python                    3.7.9                h7579374_0
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
slurmpy                   0.0.8                    pypi_0    pypi
sqlite                    3.39.4               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
typing-extensions         4.4.0                    pypi_0    pypi
wheel                     0.38.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.10.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
```

Hence, it seems like Fluffy assumed that one will always launch from a shell containing correct python and numpy version as the python call in the sbatch script uses the inherited python from the parent shell. This is not a good practice and should change so that the python call will use the python and numpy supplied (as you correctly stated above) in the requirements. So the problem is not that they are not there but that these scripts called in this way will not use them.
